--CREATE DATABASE LANCHONETE;

--USE LANCHONETE;
-- TABELA DE CLIENTES
CREATE TABLE CLIENTE(
	IDCLIENTE SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE,
	APELIDO VARCHAR(50) UNIQUE NOT NULL,
	TELEFONE VARCHAR(16),
	CPF VARCHAR(15) UNIQUE NOT NULL
);
-- TABELA DE FUNCIONÁRIOS CARALHO	
CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE,
	CPF VARCHAR(15) UNIQUE NOT NULL,
	LOGIN VARCHAR(60) UNIQUE NOT NULL,
	TELEFONE VARCHAR(16),
	SENHA VARCHAR(20) NOT NULL
);
-- MODELO DE FORNECEDOR

CREATE TABLE FORNECEDOR(
	IDFORNECEDOR SERIAL PRIMARY KEY,
	RAZAO_SOCIAL VARCHAR(100) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(11),
	CNPJ VARCHAR(40) NOT NULL UNIQUE,
	EMAIL VARCHAR(100) UNIQUE
);

CREATE TABLE ESTOQUE(
	IDESTOQUE SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	DESCRICAO VARCHAR(100),
	QUANTIDADE INT NOT NULL,
	DATA_VALIDADE DATE NOT NULL,
	VALOR_UNITARIO NUMERIC(7,2),
	DATA_ENTREGA DATE NOT NULL,
	VALOR_NOTA NUMERIC(7,2),
	ID_FORNECEDOR INT
);
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_FORNECEDOR_ESTOQUE FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR (IDFORNECEDOR);

CREATE TABLE PEDIDO(
	IDPEDIDO SERIAL PRIMARY KEY,
	PRECOTOTAL NUMERIC(7,2),
	ID_CLIENTE INT,
	ID_FUNCIONARIO INT,
	ID_ESTOQUE INT 
);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO);

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_ESTOQUE FOREIGN KEY (ID_ESTOQUE) REFERENCES ESTOQUE (IDESTOQUE);